name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Set up Git user
        run: |
          git config --global user.name "santisify"
          git config --global user.email "2812192494@qq.com"
      - name: Bump version (optional)
        run: npm version patch
      - name: Commit changes (if needed)
        run: |
          git add .
          git commit -m "Bump version" || echo "No changes to commit"
          git push origin main
      - name: npm install
        run: npm install
      - name: Rollup build
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
